logdir: ./log/log_chime3_uai/chime3
dataset_root_dir: ./data/fbank40_new_Norm_addsimu
labeled_set: train
dev_set: dev
test_set: test
max_feature_length: 2040
min_feature_length: 128
max_text_length: 212
min_text_length: 3
max_dec_timesteps: 220
batch_size: 24
shuffle: True
ls_weight: 0.05
input_dim: 40
enc_hidden_dim: 200
enc_output_dim: 200
enc_n_layers: 2
rec_n_layers: 2
subsample: [2, 1]
downsample: [2, 1]
dropout_rate: 0.2
dec_hidden_dim: 200
att_dim: 200
conv_channels: 10
conv_kernel_size: 100
att_odim: 200
embedding_dim: 50
learning_rate_m1: 0.0005
learning_rate_m2: 0.001
weight_decay_m1: 0.0000001
weight_decay_m2: 0.0000001
max_grad_norm: 5
load_model_path: ./models/chime3_uai/chime3_uai_best
retrieve_learning_rate1: 0.0005
retrieve_learning_rate2: 0.001
load_optimizer: True
init_tf_rate: 1.0
tf_start_decay_epochs: 40
tf_rate_lowerbound: 1.0
tf_decay_epochs: 90
epochs: 150
add_gaussian: False
gaussian_epoch: 20
gaussian_std: 0.075
tag: chime3_uai
model_dir: ./models/chime3_uai
model_name: chime3_uai
vocab_path: ./data/fbank40_new_Norm_addsimu/vocab_dict.p
non_lang_syms_path: ./data/fbank40_new_Norm_addsimu/non_lang_syms.p
sample_num: 5
early_stop_start_epoch: 50
early_stop: 30
test_file_name: test/predict_chime3_uai
disentangle_hidden_dim: 200
recons_hidden_dim: 300
m2_train_freq: 5
alpha: 100
z_data_path_clean: z_data/chime_uai_clean
z_data_path_noisy: z_data/chime_uai_noisy
